export default [
  {
    dom: "Creatives",
    heads: ["./assets/team/Adheena.jpeg"],
    cores: [
      "./assets/team/Shripadh Suresh.jpeg",
      "./assets/team/Shreeya Subhash Kalel.jpg",
      "./assets/team/Radhika Rajesh Bondre.jpg",
      "./assets/team/Thameem Rasheed.jpeg",
      "./assets/team/Aditya Heshi.jpeg",
      "./assets/team/Swarnima Siddhartha.jpeg",
      "./assets/team/Anay Nitin Umalkar.jpg",
      "./assets/team/Hari Govind.jpg",
    ],
  },
  {
    dom: "Sponsorship",
    heads: [
      "./assets/team/Bogam Charan Chandra.jpg",
      "./assets/team/Bevara Rohit.jpg",
      "./assets/team/Korrapati Sai Geetha Bhavana.jpeg",
    ],
    cores: [
      "./assets/team/Samuel john lakra.jpeg",
      "./assets/team/Anjireddy Anek.jpeg",
      "./assets/team/Pasalapudi Srikrishna Satvik.jpg",
      "./assets/team/Laasya Choppalli.jpeg",
      "./assets/team/Y Adarsh Reddy.jpeg",
      "./assets/team/Kosaraju Jyothsna Abhay.jpg",
      "./assets/team/Sudarshan Shivashankar.jpg",
    ],
  },
  {
    dom: "Finance",
      heads: ["./assets/team/Bommineni Vishwajith Reddy.jpg"],
    cores: [
      "./assets/team/Rakesh Varshith.jpeg",
      "./assets/team/Manikanta Varun Varma Nadimpalli.jpeg",
    ],
  },
  {
    dom: "Web",
    heads: [
      "./assets/team/Vishwa Raghava Reddy.jpg",
      "./assets/team/Poluri Rishi Manoj.jpg",
      "./assets/team/Suryaansh Jain.jpeg",
    ],
    cores: [
      "./assets/team/Adhith T.jpg",
      "./assets/team/Nihar Karthikeya.jpeg",
      "./assets/team/Ajay Krishnan K.jpeg",
      "./assets/team/LENKA YASWITH KRISHNA VAMSI.jpeg",
      "./assets/team/Kilaru Sai Manasa Veena.jpg",
      "./assets/team/Abhinay Sadineni.jpeg",
    ],
  },
  {
    dom: "Hospitality and Infra",
    heads: [
      "./assets/team/Varshini Jonnala.jpeg",
      "./assets/team/Sandhi Sai Sujith Reddy.jpg",
      "./assets/team/Suddhodhan Jajula.jpg",
    ],
    cores: [
      "./assets/team/Billa Nikila.jpeg",
      "./assets/team/Perala Anudeep.jpeg",
      "./assets/team/Kumbha Akhila.jpg",
      "./assets/team/Renikuntla Billjames.JPG",
      "./assets/team/Manoj Sai Vardan.jpg",
      "./assets/team/Venkata Abhiram.jpg",
      "./assets/team/Erraram Saikumar.jpg",
      "./assets/team/Dhanavath Tharun.jpg",
      "./assets/team/Ramavath Simhadri Nayak.jpeg",
      "./assets/team/Varun Srivastava.jpg",
      "./assets/team/Thummanapelly Shriya.jpg",
      "./assets/team/Tumarada Padmaja.jpg",
      "./assets/team/Katherapaka Nikhil.jpeg",
    ],
  },
  {
    dom: "Workshops and Publicity",
    heads: [
      "./assets/team/Sreepathi Vighnesh.jpeg",
      "./assets/team/Bangi Karthikeya.jpeg",
      "./assets/team/Thota Siri Akshara.jpg",
    ],
    cores: [
      "./assets/team/Syed Abrar.jpg",
      "./assets/team/Rohith Erelli.jpg",
      "./assets/team/Aditya Vikram Singh.jpg",
      "./assets/team/Dasari Neha vijetha.jpg",
      "./assets/team/Pasupuleti Ishwarya.jpg",
      "./assets/team/Padala Sai Kowshik.jpg",
      "./assets/team/Chunarkar Sumeeth Kumar.jpg",
      "./assets/team/Rama Jayathi.jpg",
      "./assets/team/Mudavath Vikeath.jpg",
    ],
  },
  {
    dom: "Public Relations",
    heads: [
      "./assets/team/Nikhil Singampalli.jpeg",
      "./assets/team/Siddhi Praphull Sawant.jpeg",
    ],
    cores: [
      "./assets/team/Swapnil Rawal.jpeg",
      "./assets/team/Surya Tarun.jpeg",
      "./assets/team/Rahul Metta.jpeg",
      "./assets/team/Ashish Sam.jpeg",
      "./assets/team/Santi Ashok.jpeg",
    ],
  },
  {
    dom: "Events",
    heads: [
      "./assets/team/Pasupuleti Kalyana Naga Chiranjeevi.jpeg",
      "./assets/team/Ananyan Kalepalli.jpeg",
      "./assets/team/Hiya Mehta.jpeg",
    ],
    cores: [
      "./assets/team/Deekshitha Yakasiri.jpeg",
      "./assets/team/Sriram Varma.jpeg",
      "./assets/team/Devashish Boini.jpeg",
      "./assets/team/Vishnu Shaji.jpeg",
      "./assets/team/Praveen Prakash.jpeg",
      "./assets/team/Jaswanth Kumar.jpeg",
      "./assets/team/Shiny Jillella.jpeg",
      "./assets/team/Karthikeya Hanu Prakash.jpeg",
      "./assets/team/Shaik Police Parvez.jpeg",
      "./assets/team/Sunkaraboina Uday K.jpeg",
      "./assets/team/Ruvva Suraj Kumar.jpeg",
      "./assets/team/Nidhi Raj.jpeg",
      "./assets/team/Nagarthi Niharika.jpeg",
      "./assets/team/Talasu Sowmith.jpeg",
      "./assets/team/Vadthya Ram Charan.jpeg",
    ],
  },
  {
    dom: "Pronites and Productions",
    heads: [
      "./assets/team/Baratam Sai Krishna Girish.jpeg",
      "./assets/team/Nivedya V Nair.jpeg",
      "./assets/team/Sripadmanabha S.jpeg",
    ],
    cores: [
      "./assets/team/Chakka Surya Saketh.jpeg",
      "./assets/team/Ananya S Reddy.jpeg",
      "./assets/team/Karthik Kunchala.jpeg",
      "./assets/team/K SaiTeja.jpeg",
      "./assets/team/Jp Kanishka.jpeg",
      "./assets/team/Mayank Parasramka.jpeg",
      "./assets/team/Ved Santosh Khilari.jpeg",
      "./assets/team/Vevek Manda.jpeg",
    ],
  },
  {
    dom: "Multimedia",
    heads: [
      "./assets/team/Kotichintala Aravind Siddhartha.jpeg",
      "./assets/team/Jallarapu Harshitha.jpeg",
      "./assets/team/Uttej.jpeg",
    ],
    cores: [
      "./assets/team/Sreevas T M.jpeg",
      "./assets/team/M Prince Akshay S.jpeg",
      "./assets/team/Gunnam Sri Satya Koushik.jpeg",
      "./assets/team/Tanish Reddy.jpeg",
      "./assets/team/Nenavath Arjun.jpeg",
      "./assets/team/Karri Eshmith Saideep.jpeg",
      "./assets/team/Vishnu Bhanavath.jpeg",
      "./assets/team/Banavath Venu Naik.jpeg",
    ],
  },
];
