export default [
  {
    dom: "Web",
    heads: [
      "./assets/team/Vishwa Raghava.jpg",
      "./assets/team/Rishi Manoj.jpg",
      "./assets/team/Suryaansh Jain.jpeg",
    ],
    cores: [
      "./assets/team/Adhith T.jpg",
      "./assets/team/Ajay Krishnan.jpeg",
      "./assets/team/Nihar Kartikeya.jpeg",
      "./assets/team/KRISHNA VAMSI.jpeg",
      "./assets/team/Abhinay Sadineni.png",
      "./assets/team/Manasa Veena.jpg",
    ],
  },
  {
    dom: "Creatives",
    heads: ["./assets/team/Adheena S.jpg"],
    cores: [
      "./assets/team/Harigovind P.jpeg",
      "./assets/team/Anay Nitin.jpg",
      "./assets/team/SHRIPADH SURESH.jpg",
      "./assets/team/Aditya Heshi.jpg",
      "./assets/team/Thameem Rasheed.JPG",
      "./assets/team/Radhika Rajesh.jpg",
      "./assets/team/Shreeya Subhash.jpg",
    ],
  },
  {
    dom: "Sponsorship",
    heads: [
      "./assets/team/Charan Chandra.jpg",
      "./assets/team/Bevara Rohit.jpg",
      "./assets/team/Geetha Bhavana.jpeg",
    ],
    cores: [
      "./assets/team/Samuel John.jpeg",
      "./assets/team/Anjireddy Anek.jpeg",
      "./assets/team/Srikrishna Satvik.jpg",
      "./assets/team/Adarsh Reddy.jpg",
      "./assets/team/Jyothsna Abhay.jpg",
      "./assets/team/Sudarshan Shivashankar.jpg",
    ],
  },
  {
    dom: "Finance",
      heads: ["./assets/team/Vishwajith Reddy.jpg"],
    cores: [
      "./assets/team/Rakesh Varshith.jpeg",
      "./assets/team/Varun Varma.jpeg",
    ],
  },
  {
    dom: "Hospitality and Infra",
    heads: [
      "./assets/team/Varshini Jonnala.jpeg",
      "./assets/team/Sai Sujith.jpg",
      "./assets/team/Suddhodhan Jajula.jpg",
    ],
    cores: [
      "./assets/team/Billa Nikila.jpg",
      "./assets/team/Perala Anudeep.jpeg",
      "./assets/team/Kumbha Akhila.jpg",
      "./assets/team/Renikuntla Billjames.JPG",
      "./assets/team/Sai Vardhan.PNG",
      "./assets/team/Venkata Abhiram.jpeg",
      "./assets/team/Erraram Saikumar.jpg",
      "./assets/team/Dhanavath Tharun.jpg",
      "./assets/team/Simhadri Nayak.JPG",
      "./assets/team/Varun Srivastava.jpg",
      "./assets/team/Thummanapelly Shriya.jpg",
      "./assets/team/Tumarada Padmaja.jpg",
      "./assets/team/Katherapaka Nikhil.jpeg",
    ],
  },
  {
    dom: "Workshops and Publicity",
    heads: [
      "./assets/team/Sreepathi Vighnesh.jpeg",
      "./assets/team/Bangi Karthikeya.jpeg",
      "./assets/team/Siri Akshara.jpg",
    ],
    cores: [
      "./assets/team/Syed Abrar.png",
      "./assets/team/Erelli Rohith.jpeg",
      "./assets/team/Aditya Vikram.jpg",
      "./assets/team/Neha Vijetha.jpg",
      "./assets/team/Pasupuleti Ishwarya.jpg",
      "./assets/team/Sai Kowshik.jpg",
      "./assets/team/Sumeeth Kumar.jpg",
      "./assets/team/Rama Jayathi.jpg",
      "./assets/team/Mudavath Vikeath.jpeg",
    ],
  },
  {
    dom: "Public Relations",
    heads: [
      "./assets/team/SINGAMPALLI NIKHIL.jpg",
      "./assets/team/Siddhi Praphull.jpg",
    ],
    cores: [
      "./assets/team/Swapnil Rawal.jpg",
      "./assets/team/Surya Tarun.jpg",
      "./assets/team/Rahul Metta.jpg",
      "./assets/team/Ashish Sam.jpg",
      "./assets/team/Santi Ashok.jpeg",
    ],
  },
  {
    dom: "Events",
    heads: [
      "./assets/team/NAGA CHIRANJEEVI.JPEG",
      "./assets/team/Ananyan Kalepalli.jpg",
      "./assets/team/Hiya Mehta.jpg",
    ],
    cores: [
      "./assets/team/Yakasiri Deekshitha.jpeg",
      "./assets/team/Sri Ramvarma.JPG",
      "./assets/team/Boini Devashish.jpg",
      "./assets/team/Vishnu Shaji.jpeg",
      "./assets/team/Praveen Prakash.jpg",
      "./assets/team/Jaswanth Kumar.jpg",
      "./assets/team/Jillella Shiny.jpg",
      "./assets/team/Karthikeya Hanu.jpg",
      "./assets/team/Police Parvez.jpg",
      "./assets/team/Uday Kumar.jpg",
      "./assets/team/Suraj Kumar.jpg",
      "./assets/team/Nidhi Raj.jpg",
      "./assets/team/Nagarthi Niharika.jpg",
      "./assets/team/Talasu Sowmith.jpg",
      "./assets/team/Ram Charan.jpg",
    ],
  },
  {
    dom: "Pronites and Productions",
    heads: [
      "./assets/team/Sai Krishna.jpg",
      "./assets/team/Nivedya Nair.jpg",
      "./assets/team/Sripadmanabha S.JPG",
    ],
    cores: [
      "./assets/team/Surya Saketh.jpeg",
      "./assets/team/Ananya Reddy.jpg",
      "./assets/team/Kunchala Karthik.jpg",
      "./assets/team/Kunamalla Saiteja.jpeg",
      "./assets/team/Jammagounipyatla Kanishka.jpg",
      "./assets/team/Mayank Parasramka.jpg",
      "./assets/team/Ved Santosh.jpg",
      "./assets/team/Vevek Manda.jpg",
    ],
  },
  {
    dom: "Multimedia",
    heads: [
      "./assets/team/Aravind Siddhartha.jpg",
      "./assets/team/Jallarapu Harshitha.jpg",
      "./assets/team/Uttej.jpeg",
    ],
    cores: [
      "./assets/team/Sreevas T.jpg",
      "./assets/team/Prince Akshay.jpg",
      "./assets/team/Satya Koushik.jpg",
      "./assets/team/Tanish Reddy.JPG",
      "./assets/team/Nenavath Arjun.jpg",
      "./assets/team/Eshmith Saideep.jpeg",
      "./assets/team/Banavath Vishnu.jpg",
      "./assets/team/Venu Naik.jpeg",
    ],
  },
];
