export default [
  {
    dom: "Web",
    heads: [
      "./assets/team/Vishwa Raghava Reddy.jpg",
      "./assets/team/Poluri Rishi Manoj.jpg",
      "./assets/team/Suryaansh Jain.jpeg",
    ],
    cores: [
      "./assets/team/Adhith T.jpg",
      "./assets/team/Ajay Krishnan K.jpeg",
      "./assets/team/Nihar Kartikeya.jpeg",
      "./assets/team/LENKA YASWITH KRISHNA VAMSI.jpeg",
      "./assets/team/Abhinay Sadineni.png",
      "./assets/team/Kilaru Sai Manasa Veena.jpg",
    ],
  },
  {
    dom: "Creatives",
    heads: ["./assets/team/Adheena S.jpg"],
    cores: [
      "./assets/team/Harigovind P.jpeg",
      "./assets/team/Anay Nitin Umalkar.jpg",
      "./assets/team/SHRIPADH SURESH.jpg",
      "./assets/team/Aditya Heshi.jpg",
      "./assets/team/Thameem Rasheed.JPG",
      "./assets/team/Radhika Rajesh Bondre.jpg",
      "./assets/team/Shreeya Subhash Kalel.jpg",
    ],
  },
  {
    dom: "Sponsorship",
    heads: [
      "./assets/team/Bogam Charan Chandra.jpg",
      "./assets/team/Bevara Rohit.jpg",
      "./assets/team/Korrapati Sai Geetha Bhavana.jpeg",
    ],
    cores: [
      "./assets/team/Samuel John Lakra.jpeg",
      "./assets/team/Anjireddy Anek.jpeg",
      "./assets/team/Pasalapudi Srikrishna Satvik.jpg",
      "./assets/team/Y Adarsh Reddy.jpg",
      "./assets/team/Kosaraju Jyothsna Abhay.jpg",
      "./assets/team/Sudarshan Shivashankar.jpg",
    ],
  },
  {
    dom: "Finance",
      heads: ["./assets/team/Bommineni Vishwajith Reddy.jpg"],
    cores: [
      "./assets/team/Palem Rakesh Varshith.jpeg",
      "./assets/team/Manikanta Varun Varma Nadimpalli.jpeg",
    ],
  },
  {
    dom: "Hospitality and Infra",
    heads: [
      "./assets/team/Varshini Jonnala.jpeg",
      "./assets/team/Sandhi Sai Sujith Reddy.jpg",
      "./assets/team/Suddhodhan Jajula.jpg",
    ],
    cores: [
      "./assets/team/Billa Nikila.jpg",
      "./assets/team/Perala Anudeep.jpeg",
      "./assets/team/Kumbha Akhila.jpg",
      "./assets/team/Renikuntla Billjames.JPG",
      "./assets/team/Thurupalli Manoj Sai Vardhan.PNG",
      "./assets/team/V Venkata Abhiram.jpeg",
      "./assets/team/Erraram Saikumar.jpg",
      "./assets/team/Dhanavath Tharun.jpg",
      "./assets/team/Ramavath Simhadri Nayak.JPG",
      "./assets/team/Varun Srivastava.jpg",
      "./assets/team/Thummanapelly Shriya.jpg",
      "./assets/team/Tumarada Padmaja.jpg",
      "./assets/team/Katherapaka Nikhil.jpeg",
    ],
  },
  {
    dom: "Workshops and Publicity",
    heads: [
      "./assets/team/Sreepathi Vighnesh.jpeg",
      "./assets/team/Bangi Karthikeya.jpeg",
      "./assets/team/Thota Siri Akshara.jpg",
    ],
    cores: [
      "./assets/team/Syed Abrar.png",
      "./assets/team/Erelli Rohith.jpeg",
      "./assets/team/Aditya Vikram Singh.jpg",
      "./assets/team/Dasari Neha Vijetha.jpg",
      "./assets/team/Pasupuleti Ishwarya.jpg",
      "./assets/team/Padala Sai Kowshik.jpg",
      "./assets/team/Chunarkar Sumeeth Kumar.jpg",
      "./assets/team/Rama Jayathi.jpg",
      "./assets/team/Mudavath Vikeath.jpeg",
    ],
  },
  {
    dom: "Public Relations",
    heads: [
      "./assets/team/SINGAMPALLI NIKHIL.jpg",
      "./assets/team/Siddhi Praphull Sawant.jpg",
    ],
    cores: [
      "./assets/team/Swapnil Rawal.jpg",
      "./assets/team/Jagarapu Surya Tarun.jpg",
      "./assets/team/Rahul Metta.jpg",
      "./assets/team/Ashish Sam.jpg",
      "./assets/team/Santi Ashok.jpeg",
    ],
  },
  {
    dom: "Events",
    heads: [
      "./assets/team/PASUPULETI KALYANA NAGA CHIRANJEEVI.JPEG",
      "./assets/team/Ananyan Kalepalli_AK.jpg",
      "./assets/team/Hiya Mehta.jpg",
    ],
    cores: [
      "./assets/team/Yakasiri Deekshitha.jpeg",
      "./assets/team/Yembadi Sri Ramvarma.JPG",
      "./assets/team/Boini Devashish.jpg",
      "./assets/team/Vishnu Shaji.jpeg",
      "./assets/team/Praveen Prakash Ayila.jpg",
      "./assets/team/Koram Jaswanth Kumar.jpg",
      "./assets/team/Jillella Shiny.jpg",
      "./assets/team/Karthikeya Hanu Prakash Kanithi.jpg",
      "./assets/team/Shaik Police Parvez.jpg",
      "./assets/team/Sunkaraboina Uday Kumar.jpg",
      "./assets/team/Ruvva Suraj Kumar.jpg",
      "./assets/team/Nidhi Raj.jpg",
      "./assets/team/Nagarthi Niharika.jpg",
      "./assets/team/Talasu Sowmith.jpg",
      "./assets/team/Vadthya Ram Charan.jpg",
    ],
  },
  {
    dom: "Pronites and Productions",
    heads: [
      "./assets/team/Baratam Sai Krishna Girish.jpg",
      "./assets/team/Nivedya V Nair.jpg",
      "./assets/team/Sripadmanabha S.JPG",
    ],
    cores: [
      "./assets/team/Surya Saketh Chakka.jpeg",
      "./assets/team/Ananya S Reddy.jpg",
      "./assets/team/Kunchala Karthik.jpg",
      "./assets/team/Kunamalla Saiteja.jpeg",
      "./assets/team/Jammagounipyatla Kanishka.jpg",
      "./assets/team/Mayank Parasramka.jpg",
      "./assets/team/Ved Santosh Khilari.jpg",
      "./assets/team/Vevek Manda.jpg",
    ],
  },
  {
    dom: "Multimedia",
    heads: [
      "./assets/team/Kotichintala Aravind Siddhartha.jpg",
      "./assets/team/Jallarapu Harshitha.jpg",
      "./assets/team/Uttej.jpeg",
    ],
    cores: [
      "./assets/team/Sreevas T M.jpg",
      "./assets/team/M Prince Akshay S.jpg",
      "./assets/team/Gunnam Sri Satya Koushik.jpg",
      "./assets/team/Sanikommu Tanish Reddy.JPG",
      "./assets/team/Nenavath Arjun.jpg",
      "./assets/team/Karri Eshmith Saideep.jpeg",
      "./assets/team/Banavath Vishnu.jpg",
      "./assets/team/Banavath Venu Naik.jpeg",
    ],
  },
];
